# Generated by Django 3.1.7 on 2021-06-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='postid',
            field=models.IntegerField(),
        ),
    ]
