# Generated by Django 3.1.7 on 2021-06-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_likes_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
