# Generated by Django 3.1.7 on 2021-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210617_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
