# Generated by Django 3.1.7 on 2021-06-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210617_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='postid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.posts'),
            preserve_default=False,
        ),
    ]
