# Generated by Django 3.1.7 on 2021-06-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210617_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
